---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: jenkins
spec:
  minReadySeconds: 5
  replicas: 3
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
      name: jenkins
    spec:
      containers:
        - image: jenkins/jenkins:lts-jdk11
          name: jenkins
          ports:
            - containerPort: 8080
              protocol: TCP