---
apiVersion: v1
kind: Service
metadata:
  name: servicefornginx
  labels: 
    serv: nginx
spec: 
  type: NodePort
  selector: 
    app: nginx
    ver: "1.23"
  ports:
    - name: nginxwebport
      port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 32678

  
